# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  preview:
    cmds:
      - quarto preview
    desc: Preview website

  new-post:
    dir: posts
    cmds:
      - mkdir -p {{.POST_NAME}}
      - cp _template.qmd ./{{.POST_NAME}}/index.qmd
    requires:
      vars:
        - name: POST_NAME
    status:
      - test -d {{.POST_NAME}}
    desc: Create new blog post
